### ISSUE TITLE
create angular recipes

### ISSUE THREAD

**Issue by chrisdias** [weinand/vscode-recipes#1]
A simple Angular app: https://github.com/johnpapa/angular-tour-of-heroes

``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "sourceMaps": true,
            "url": "http://localhost:4200",
            "webRoot": "${workspaceRoot}",
            "sourceMapPathOverrides": {
                "webpack:///./*": "${webRoot}/*"
            }
        }
    ]
}
```

The `sourceMapPathOverrides` was the important section...

**Comment by tonysneed** [comment]
I've got a [gist](https://gist.github.com/tonysneed/ced37e8f7d8e72a07aaf35b60241f041) with launch configurations for Chrome debugging and Angular CLI.  It has configs both for `ng serve` and `ng test`.  Would you accept a PR?

**Comment by weinand** [comment]
@tonysneed sure, a PR would be really great!
Ideally the PR could contain a full subfolder "Angular" with a minimal sample, a readme.md and the launch config (similar to the two other subfolders).

**Comment by auchenberg** [comment]
@tonysneed @weinand I'm in the middle of prepping a VS Code blog post about Angular (angular-cli) + our Chrome debugger. Would to be able to back reference this repo.

**Comment by tonysneed** [comment]
Terrific, I'll get started on it. It's nice to have an example as a starting point. :)

**Comment by tonysneed** [comment]
@weinand @auchenberg See PR #2.

**Comment by tonysneed** [comment]
@weinand Thanks for merging my PR .. Happy to be of service! :bow:

**Comment by tonysneed** [comment]
Updated the README in PR #4.
Updated launch.json in PR #5.

**Comment by tonysneed** [comment]
Removed sourceMaps, trace, userDataDir from JSON in README.md file in PR #6.

**Comment by weinand** [comment]
@tonysneed @auchenberg thanks for your help on this recipe!

@tonysneed an official "Thank You" will appear in the June release notes.

**Comment by tonysneed** [comment]
@weinand Glad I could contribute! 😎
