### ISSUE TITLE
Is it possible to add e2e debugging?

### ISSUE THREAD

**Issue by RobotnickIsrael** [weinand/vscode-recipes#12]
I'm looking how do to it for a very long time now,
it really slows us down not having the ability to debug from the code.

(I am using "e2e:debug": "ng e2e -ee --webdriver-update=false --aot=false --proxy-config proxy.conf.json" "

Thanks

**Comment by auchenberg** [comment]
@RobotnickIsrael Can you provide a new more details on your setup? Are you using Angular-cli? We have an open issue for `ng test`, https://github.com/weinand/vscode-recipes/issues/9

**Comment by auchenberg** [comment]
There's a guide here on how you debug Protractor, which seem to be powering `ng e2e`. https://blogs.msdn.microsoft.com/wushuai/2016/08/24/debug-protractor-script-in-visual-studio-code/

**Comment by RobotnickIsrael** [comment]
Yes I am using angular-cli.
I'm not talking about unit testing (aka ng test) but protractor.
I can use this documentation even though I'm using angular-cli?
I'll try and update.
Thank you very much

**Comment by auchenberg** [comment]
@RobotnickIsrael I've spend a little time writing a guide on you to make it work: https://github.com/weinand/vscode-recipes/pull/14

**Comment by RobotnickIsrael** [comment]
@auchenberg Thank you very mich (:
I tried that [solution ](https://github.com/weinand/vscode-recipes/pull/14/commits/461561261b4ce91994ee7db3181011cff41f9dcb) but it didn't work.

1. I have node 7.7.3 so I changed the progotocol to legacy.
2. I loaded ng server (via npm start)
3. I launched debugging using "Launch ng e2e"

Nothing happens. (Meaning it think for a few seconds and goes off)

But is it right to use ng serve and not ng e2e?
Since we want to use the app.e2e-spec.ts no?
And we want the ChroneDriver and Element Explorer.

I tried launching the debug on ng e2e but it didn't work as well.
I also tried adding '"port": 5858 ' to the launch.json (launch ng e2e)
but again it doesn't really work.
when I launch the e2e I get this on the console:

[16:38:25] I/direct - Using ChromeDriver directly...
[16:39:19] I/protractor -
[16:39:19] I/protractor - ------- Element Explorer -------
[16:39:19] I/protractor - Starting WebDriver debugger in a child process. Element Explorer is still beta, please report issues at github.co
m/angular/protractor
[16:39:19] I/protractor -
[16:39:19] I/protractor - Type <tab> to see a list of locator strategies.
[16:39:19] I/protractor - Use the `list` helper function to find elements by strategy:
[16:39:19] I/protractor -   e.g., list(by.binding('')) gets all bindings.
[16:39:19] I/protractor -
Starting debugger agent.
(node:20600) DeprecationWarning: node --debug is deprecated. Please use node --inspect instead.
Debugger listening on 127.0.0.1:5858


Any ideas?

Thanks again!
Israel

**Comment by auchenberg** [comment]
@RobotnickIsrael `ng e2e` runs `ng serve` + protractor behind the scenes as a unified command. We need to start `protractor` process with remote debugging enabled, so that's the reason for why you have to run `ng serve` manually, as VS Code will launch `protractor` as a part of the configuration.

I just tried installing node `7.7.3`, and if you use ` "protocol": "inspector",` then breakpoints as hit in the e2e tests.

**Comment by daBishMan** [comment]
thank you for the PR @auchenberg, I think the issue might, at least to my eyes, it seems step #3 is missing which is to run the tests once before you can see the code getting attached, but for me it works.  Thanks a million

My environment:  
> @angular/cli: 1.1.1
node: 8.1.2
os: win32 x64
@angular/animations: 4.2.6
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/core: 4.2.6
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/router: 4.2.6
@angular/cli: 1.1.1
@angular/compiler-cli: 4.2.6
@angular/language-service: 4.2.6

**Comment by daBishMan** [comment]
@angular/cli: 1.1.1
node: 8.1.2
os: win32 x64
@angular/animations: 4.2.6
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/core: 4.2.6
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/router: 4.2.6
@angular/cli: 1.1.1
@angular/compiler-cli: 4.2.6
@angular/language-service: 4.2.6

**Comment by auchenberg** [comment]
@daBishMan I think this could be a problem with your angular-cli version. Can you try to upgrade to `1.1.3`? https://github.com/angular/angular-cli/releases
